name: SpaceCadetPinballDVD Build

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii"]
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        yes | sudo dkp-pacman -Sy
        yes | sudo dkp-pacman -Syu
        yes | sudo dkp-pacman -S wii-sdl
        yes | sudo dkp-pacman -S wii-sdl_mixer
        yes | sudo dkp-pacman -S wii-sdl_gfx
        make -f Makefile -j2

    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: |
        mkdir dist/PinballDVD
        cp SpaceCadetPinball-dvd.dol dist/PinballDVD/main.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with:
        name: PinballDVD
        path: |
          dist/PinballDVD/
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/wii'

    steps:
    - name: Checkout snes9xgx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Re-zip artifacts
      run: |
        cd dist
        zip -r PinballDVD.zip PinballDVF
        
    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: false
        tag: Pre-release
        artifacts: "dist/*.zip"
